### ISSUE TITLE
Failed to compile with Hive 2.1.0

### ISSUE THREAD

**Issue by gilv** [klarna/HiveRunner#56]
I tried to compile project with Hive 2.1.0.
Got

ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /HiveRunner/src/main/java/com/klarna/hiverunner/HiveServerContainer.java:[23,39] cannot find symbol
  symbol:   class VariableSubstitution
  location: package org.apache.hadoop.hive.ql.parse
[ERROR] /HiveRunner/src/main/java/com/klarna/hiverunner/HiveServerContainer.java:[202,12] cannot find symbol
  symbol:   class VariableSubstitution
  location: class com.klarna.hiverunner.HiveServerContainer
[INFO] 2 errors

**Comment by PelleUllberg** [comment]
Hi, 

Take a look at branch https://github.com/klarna/HiveRunner/tree/hive-2.1.0-NPE-at-msck-repair

It compiles, but not all tests succeed on my local build ATM.

/Pelle

**Comment by massdosage** [comment]
Work to get HiveRunner working with Hive 2.3.x is happening here: https://github.com/klarna/HiveRunner/tree/Hive-2.3.0
