### ISSUE TITLE
Hive 2.1.0

### ISSUE THREAD

**Issue by workasr** [klarna/HiveRunner#50]
I hope this helps anyone who wants to use Hiverunner with Hive 2.1.0.
I had to make some modifications for the tool to work on 2.1.0:
1.  Did not work on Windows,  I had to run on Linux (see #45 )
2.  Switched Metastore to embedded Derby
   - set "datanucleus.schema.autoCreateAll" to "true"
   - modify StandaloneHiveServerContext.java
   
   ```
   //metaStorageUrl = "jdbc:hsqldb:mem:" + UUID.randomUUID().toString();
   metaStorageUrl = "jdbc:derby:;databaseName=" + basedir.getRoot().getAbsolutePath() + "/metastore_db";
   ```
3.  Hive API change
   - HiveServerContainer.java
   
   ```
   21a22
   > import org.apache.hadoop.hive.conf.HiveVariableSource;
   23c24
   < import org.apache.hadoop.hive.ql.parse.VariableSubstitution;
   ---
   > import org.apache.hadoop.hive.conf.VariableSubstitution;
   206c207,214
   <         return new VariableSubstitution();
   ---
   >         final SessionState ss = currentSessionState;
   >         return new VariableSubstitution(new HiveVariableSource() {
   >
   >                       @Override
   >                       public Map<String, String> getHiveVariable() {
   >                               return ss.getHiveVariables();
   >                       }
   >               });
   ```

**Comment by PelleUllberg** [comment]
Awesome! 

I haven't yet had the time to play around with hive 2.x myself, but could you elaborate a bit on why the switch to derby was needed? 

When I replaced Derby with hsqldb back in the days it was because of performance reasons. Hsqldb performed so much faster than Derby at that time. In particular I think it was the spinup that differed significantly and since HiveRunner spins up a new metastore for every unit test that made a huge difference for larger test suites.

Have you noticed any performance drops? It is off course hard to tell because hive 2.x is also very different from 1.x. I'll try to find some time to look at this in a couple pw weeks.

Thanks
/Pelle

**Comment by PelleUllberg** [comment]
Ping!

Could you create a branch with these changes? I'm having trouble replicating your success :(

/Pelle

**Comment by patduin** [comment]
Hi Per,

I am updating one of our hive metastore testing tools (https://github.com/HotelsDotCom/beeju) to use Hive 2.1.1 and I am seeing similar issues with HSQL DB looks like Hive doesn't support it anymore due to transactions. We're hitting this code in hive: https://github.com/apache/hive/blob/rel/release-2.1.1/metastore/src/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java#L1994

So we are considering going back to Derby as well, have you got any other recommendations?

Thanks,
 Patrick

**Comment by chemikadze** [comment]
@PelleUllberg Just got very similar problem with HSQL. I have not quite certain that it is the only issue, but it feels like in my case deadlock is appearing because of this statement:
```
ALTER TABLE TBL_PRIVS ADD CONSTRAINT TBL_PRIVS_FK1 FOREIGN KEY (TBL_ID) REFERENCES TBLS (TBL_ID) 
```
being executed in _another_ session during createTable operation, even though it is supposed to run as part of the same transaction. Because TBLS object is getting created from another, "original" transaction, ad-hoc session created for DDL session can not proceed. In theory, if hive schema would be created not lazily, but in advance (by schematool?), it would resolve that particular deadlock.

It actually feels like combination of issues in hsqldb (it could not deadlock in cases like that) and datanucleus-rdbms (it could use same transaction/connection for all effects within persistObjects operation). Unfortunately is reproducing on all versions of hsqldb 2.x and dn-rdbms 4.1.x, including latest ones.

@patduin Have you been relying on automatic schema creation in hive, or have been triggering it before running any operations?

Here is representative stack trace:
```
"41440ce4-daf2-4c0f-943e-ec0ffaed3808 Thread-1" #14 prio=5 os_prio=31 tid=0x00007fedd3adc000 nid=0x5f03 waiting on condition [0x0000000124b6a000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007b4295138> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at org.hsqldb.lib.CountUpDownLatch.await(CountUpDownLatch.java:58)
	at org.hsqldb.Session.executeCompiledStatement(Session.java:1319)
	at org.hsqldb.Session.executeDirectStatement(Session.java:1217)
	at org.hsqldb.Session.execute(Session.java:995)
	- locked <0x00000007b4294ff8> (a org.hsqldb.Session)
	at org.hsqldb.jdbc.JDBCStatement.fetchResult(JDBCStatement.java:1809)
	at org.hsqldb.jdbc.JDBCStatement.execute(JDBCStatement.java:638)
	- locked <0x00000007b432d458> (a org.hsqldb.jdbc.JDBCStatement)
	at org.datanucleus.store.rdbms.table.AbstractTable.executeDdlStatement(AbstractTable.java:879)
	at org.datanucleus.store.rdbms.table.TableImpl.createForeignKeys(TableImpl.java:522)
	at org.datanucleus.store.rdbms.table.TableImpl.createConstraints(TableImpl.java:426)
	at org.datanucleus.store.rdbms.RDBMSStoreManager$ClassAdder.performTablesValidation(RDBMSStoreManager.java:3444)
	at org.datanucleus.store.rdbms.RDBMSStoreManager$ClassAdder.run(RDBMSStoreManager.java:2877)
	at org.datanucleus.store.rdbms.AbstractSchemaTransaction.execute(AbstractSchemaTransaction.java:119)
	at org.datanucleus.store.rdbms.RDBMSStoreManager.manageClasses(RDBMSStoreManager.java:1608)
	at org.datanucleus.store.rdbms.RDBMSStoreManager.getDatastoreClass(RDBMSStoreManager.java:671)
	at org.datanucleus.store.rdbms.RDBMSStoreManager.getPropertiesForGenerator(RDBMSStoreManager.java:2069)
	at org.datanucleus.store.AbstractStoreManager.getStrategyValue(AbstractStoreManager.java:1271)
	- locked <0x0000000781dc93a0> (a org.datanucleus.store.rdbms.RDBMSStoreManager)
	at org.datanucleus.ExecutionContextImpl.newObjectId(ExecutionContextImpl.java:3759)
	at org.datanucleus.state.StateManagerImpl.setIdentity(StateManagerImpl.java:2267)
	at org.datanucleus.state.StateManagerImpl.initialiseForPersistentNew(StateManagerImpl.java:484)
	at org.datanucleus.state.StateManagerImpl.initialiseForPersistentNew(StateManagerImpl.java:120)
	at org.datanucleus.state.ObjectProviderFactoryImpl.newForPersistentNew(ObjectProviderFactoryImpl.java:218)
	at org.datanucleus.ExecutionContextImpl.persistObjectInternal(ExecutionContextImpl.java:2078)
	at org.datanucleus.ExecutionContextImpl.persistObjectWork(ExecutionContextImpl.java:1922)
	at org.datanucleus.ExecutionContextImpl.persistObjects(ExecutionContextImpl.java:1867)
	at org.datanucleus.ExecutionContextThreadedImpl.persistObjects(ExecutionContextThreadedImpl.java:231)
	at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistentAll(JDOPersistenceManager.java:764)
	at org.apache.hadoop.hive.metastore.ObjectStore.createTable(ObjectStore.java:1041)

```

**Comment by narendracs** [comment]
@PelleUllberg 
I am trying to test hive transactions queries using hiverunner
Took latest code and build mvn build in my local , I am able to build the jar. I am using hive runner in another project, added pom dependency.

All the queries that involve MR job is failing with specific exception regarding serialization. 
Query for creating table and setting parameters are fine but query for insert into or select * from are failing 
looks like things are failing while writing data to temp file , not sure how to resolve this. Any idea ?

java.lang.IllegalArgumentException: Failed to executeQuery Hive query insert into table nasingh.xxx values(1): Error running query: java.lang.NoClassDefFoundError: com/esotericsoftware/kryo/KryoException
at com.klarna.hiverunner.HiveServerContainer.executeStatement(HiveServerContainer.java:131)
at com.klarna.hiverunner.HiveServerContainer.executeScript(HiveServerContainer.java:143)
atcom.klarna.hiverunner.builder.HiveShellBase.executeScriptWithCommandShellEmulation(HiveShellBase.java:326)
at com.klarna.hiverunner.builder.HiveShellBase.execute(HiveShellBase.java:113)

**Comment by patduin** [comment]
@chemikadze I've run all hiveRunner tests (but using Derby instead of hsql) and in my test I don't use auto schema creation. I don't recall seeing similar stacktraces.

**Comment by massdosage** [comment]
We have tested the 4.0.0 release against Hive 2.3.3 and HIve 2.1.0. Admittedly we haven't tested all Hive functionality but our test cases (in downstream projects) passed. So I've closed this, we can open new tickets if users report other things not working in 4.0.0
